global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flask-app"
    static_configs:
      - targets: ["flask-app:5000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://flask-app:5000/health
          - http://flask-app:5000/error
          - http://flask-app:5000/slow
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
